networks:
  1panel-network:
    external: true
services:
  speedtest-tracker:
    image: "linuxserver/speedtest-tracker:1.14.5"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL}
      - DB_CONNECTION=sqlite
      - DISPLAY_TIMEZONE=${DISPLAY_TIMEZONE}
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE:-}
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS:-}
      - PRUNE_RESULTS_OLDER_THAN=${PRUNE_RESULTS_OLDER_THAN:-0}
    labels:
      createdBy: "Apps"
