networks:
  1panel-network:
    external: true
services:
  nginx:
    image: "linuxserver/nginx:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - NGINX_AUTORELOAD=${NGINX_AUTORELOAD:-false}
      - NGINX_AUTORELOAD_WATCHLIST=${NGINX_AUTORELOAD_WATCHLIST:-}
    labels:
      createdBy: "Apps"
