services:
  1panel:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ${DATA_PATH}:${DATA_PATH}
      - /root:/root
    environment:
      - TZ=${TIME_ZONE}
      - PORT=${PANEL_APP_PORT_HTTP}
      - USERNAME=${PANEL_ADMIN_USERNAME}
      - PASSWORD=${PANEL_ADMIN_PASSWORD}
      - ENTRANCE=${PANEL_ENTRANCE}
      - BASE_DIR=${DATA_PATH}
      - RESET=false
    image: moelin/1panel:v1
    labels:
      createdBy: Apps
