networks:
  1panel-network:
    external: true
services:
  piper:
    image: "linuxserver/piper:2.2.2"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_WYOMING}:10200"
    volumes:
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - PIPER_VOICE=${PIPER_VOICE}
      - LOCAL_ONLY=${LOCAL_ONLY:-}
      - PIPER_LENGTH=${PIPER_LENGTH:-1.0}
      - PIPER_NOISE=${PIPER_NOISE:-0.667}
      - PIPER_NOISEW=${PIPER_NOISEW:-0.333}
      - PIPER_SPEAKER=${PIPER_SPEAKER:-0}
      - NO_STREAMING=${NO_STREAMING:-}
    labels:
      createdBy: "Apps"
