services:
  1panel:
    container_name: ${CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}:/opt
    environment:
      - TZ=${TIME_ZONE}
      - PORT=${PANEL_APP_PORT_HTTP}
      - USERNAME=${PANEL_ADMIN_USERNAME}
      - PASSWORD=${PANEL_ADMIN_PASSWORD}
      - ENTRANCE=${PANEL_ENTRANCE}
      - BASE_DIR=/opt
      - RESET=false
    image: moelin/1panel:v2.2.3
    labels:
      createdBy: Apps
