services:
  odoo:
    image: "odoo:19.0"
    container_name: ${CONTAINER_NAME}
    restart: always
    depends_on:
      odoo-db:
        condition: service_healthy
    networks:
      - 1panel-network
      - odoo-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8069"
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        cat > /tmp/odoo.conf <<EOF
        [options]
        addons_path = /mnt/extra-addons
        data_dir = /var/lib/odoo
        admin_passwd = ${ODOO_MASTER_PASSWORD}
        EOF
        exec /entrypoint.sh odoo server -c /tmp/odoo.conf
    environment:
      - TZ=${TZ}
      - HOST=odoo-db
      - PORT=5432
      - USER=odoo
      - PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "${APP_DATA_DIR}/odoo-data:/var/lib/odoo"
      - "${APP_DATA_DIR}/addons:/mnt/extra-addons"
    labels:
      createdBy: "Apps"

  odoo-db:
    image: "postgres:15"
    container_name: ${CONTAINER_NAME}-db
    restart: always
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "${APP_DATA_DIR}/postgres:/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
  odoo-network:
    driver: bridge
