services:
  dokku:
    image: "dokku/dokku:0.38.28@sha256:f9916e8ce6142cea945fe97fb0b9353735ea8813974a28e0a18e7f15e77ee7a5"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    network_mode: bridge
    environment:
      - DOKKU_HOSTNAME=${DOKKU_HOSTNAME}
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku
      - DOKKU_LIB_HOST_ROOT=/var/lib/dokku/var/lib/dokku
      - TZ=${TZ}
    volumes:
      - "/var/lib/dokku:/mnt/dokku"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${PANEL_APP_PORT_SSH}:22"
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    labels:
      createdBy: "Apps"
