networks:
  1panel-network:
    external: true
services:
  qbittorrent:
    image: "linuxserver/qbittorrent:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:${PANEL_APP_PORT_HTTP}"
      - "${PANEL_APP_PORT_BT_DOWNLOAD_LISTENER}:${PANEL_APP_PORT_BT_DOWNLOAD_LISTENER}"
      - "${PANEL_APP_PORT_BT_DOWNLOAD_LISTENER}:${PANEL_APP_PORT_BT_DOWNLOAD_LISTENER}/udp"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${DOWNLOAD_PATH}:/downloads"
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=${PANEL_APP_PORT_HTTP}
      - TORRENTING_PORT=${PANEL_APP_PORT_BT_DOWNLOAD_LISTENER}
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"
