additionalProperties:
  formFields:
  - default: ./data
    edit: true
    envKey: DATA_PATH
    labelEn: Config folder path
    labelZh: 数据文件夹路径
    required: true
    type: text
    label:
      en: Config folder path
      zh: 数据文件夹路径
      zh-Hant: 設定資料夾路徑
      ja: 設定フォルダーパス
      ko: 설정 폴더 경로
      ru: Путь к папке конфигурации
      ms: Laluan Folder Konfigurasi
      pt-br: Caminho da pasta de configuração
  - default: 6052
    disabled: true
    envKey: PANEL_APP_PORT_HTTP
    labelEn: Port
    labelZh: HTTP 端口
    required: true
    rule: paramPort
    type: number
    edit: false
    label:
      en: Port
      zh: HTTP 端口
      zh-Hant: HTTP 連接埠
      ja: HTTPポート
      ko: HTTP 포트
      ru: HTTP-порт
      ms: Port HTTP
      pt-br: Porta HTTP
  - default: admin
    edit: true
    envKey: ESPHOME_USERNAME
    labelEn: Dashboard Username
    labelZh: 控制台用户名
    required: true
    type: text
    label:
      en: Dashboard Username
      zh: 控制台用户名
      zh-Hant: 控制台使用者名稱
      ja: ダッシュボードユーザー名
      ko: 대시보드 사용자 이름
      ru: Имя пользователя панели
      ms: Nama Pengguna Dashboard
      pt-br: Usuario do Dashboard
  - default: ''
    edit: true
    envKey: ESPHOME_PASSWORD
    labelEn: Dashboard Password
    labelZh: 控制台密码
    random: true
    required: true
    rule: paramComplexity
    type: password
    label:
      en: Dashboard Password
      zh: 控制台密码
      zh-Hant: 控制台密碼
      ja: ダッシュボードパスワード
      ko: 대시보드 비밀번호
      ru: Пароль панели
      ms: Kata Laluan Dashboard
      pt-br: Senha do Dashboard
  - default: Asia/Shanghai
    edit: true
    envKey: TZ
    labelEn: Timezone
    labelZh: 时区
    label:
      en: Timezone
      zh: 时区
      zh-Hant: 時區
      ja: タイムゾーン
      ko: 시간대
      ru: Часовой пояс
      ms: Zon waktu
      pt-br: Fuso horário
    required: true
    type: text
