networks:
  1panel-network:
    external: true
services:
  netbootxyz:
    image: "linuxserver/netbootxyz:0.7.6"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
      - "${PANEL_APP_PORT_TFTP}:69/udp"
      - "${PANEL_APP_PORT_ASSETS}:80"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${ASSETS_PATH}:/assets"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - MENU_VERSION=${MENU_VERSION}
      - PORT_RANGE=${PORT_RANGE:-30000:30010}
      - SUBFOLDER=${SUBFOLDER}
      - NGINX_PORT=80
      - WEB_APP_PORT=3000
    labels:
      createdBy: "Apps"
