networks:
  1panel-network:
    external: true
services:
  mylar3:
    image: "linuxserver/mylar3:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:8090"
    volumes:
      - "${CONFIG_PATH}:/config"
      - "${COMICS_PATH}:/comics"
      - "${DOWNLOAD_PATH}:/downloads"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"
