networks:
  1panel-network:
    external: true
services:
  doplarr:
    image: "linuxserver/doplarr:latest"
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - "${CONFIG_PATH}:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
      - DISCORD__TOKEN=${DISCORD_TOKEN}
      - OVERSEERR__API=${OVERSEERR_API}
      - OVERSEERR__URL=${OVERSEERR_URL}
      - RADARR__API=${RADARR_API}
      - RADARR__URL=${RADARR_URL}
      - SONARR__API=${SONARR_API}
      - SONARR__URL=${SONARR_URL}
      - SONARR__QUALITY_PROFILE=${SONARR_QUALITY_PROFILE}
      - RADARR__QUALITY_PROFILE=${RADARR_QUALITY_PROFILE}
      - SONARR__ROOTFOLDER=${SONARR_ROOTFOLDER}
      - RADARR__ROOTFOLDER=${RADARR_ROOTFOLDER}
      - SONARR__LANGUAGE_PROFILE=${SONARR_LANGUAGE_PROFILE}
      - OVERSEERR__DEFAULT_ID=${OVERSEERR_DEFAULT_ID}
      - DISCORD__MAX_RESULTS=${DISCORD_MAX_RESULTS}
      - DISCORD__REQUESTED_MSG_STYLE=${DISCORD_REQUESTED_MSG_STYLE}
      - PARTIAL_SEASONS=${PARTIAL_SEASONS}
      - LOG_LEVEL=${LOG_LEVEL}
      - JAVA_OPTS=${JAVA_OPTS:-}
    labels:
      createdBy: "Apps"
