services:
  dokku:
    image: "dokku/dokku:0.38.29@sha256:8ae6486c0c3709e8b367ebece7b30e4055e99b8ee9aa81f3d7cc807a9a2d60a1"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    network_mode: bridge
    environment:
      - DOKKU_HOSTNAME=${DOKKU_HOSTNAME}
      - DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku
      - DOKKU_LIB_HOST_ROOT=/var/lib/dokku/var/lib/dokku
      - TZ=${TZ}
    volumes:
      - "/var/lib/dokku:/mnt/dokku"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${PANEL_APP_PORT_SSH}:22"
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    labels:
      createdBy: "Apps"
